global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "telegraf"
    scrape_interval: 5s
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
