name: Audit-Qcm CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-step:
    runs-on: ubuntu-latest # L'environnement d'exécution

    steps:
      # 1. Cloner le dépôt
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 📤 Copier le fichier .env du back
        run: |
          cd /home/runner/work/audit-qcm/audit-qcm/apis
          touch .env
          echo ${{ secrets.APIS_ENV_TZ }} >> .env
          echo ${{ secrets.APIS_ENV_PORT }} >> .env
          echo ${{ secrets.APIS_ENV_HOST }} >> .env
          echo ${{ secrets.APIS_ENV_LOG_LEVEL }} >> .env
          echo ${{ secrets.APIS_ENV_APP_KEY }} >> .env
          echo ${{ secrets.APIS_ENV_NODE_ENV }} >> .env
          echo ${{ secrets.APIS_ENV_DB_HOST }} >> .env
          echo ${{ secrets.APIS_ENV_DB_PORT }} >> .env
          echo ${{ secrets.APIS_ENV_DB_USER }} >> .env
          echo ${{ secrets.APIS_ENV_DB_PASSWORD }} >> .env
          echo ${{ secrets.APIS_ENV_DB_DATABASE }} >> .env
          echo ${{ secrets.APIS_ENV_SMTP_HOST }} >> .env
          echo ${{ secrets.APIS_ENV_SMTP_PORT }} >> .env
          echo ${{ secrets.APIS_ENV_SMTP_USERNAME }} >> .env
          echo ${{ secrets.APIS_ENV_SMTP_PASSWORD }} >> .env
          echo ${{ secrets.APIS_ENV_CACHE_VIEWS }} >> .env
          echo ${{ secrets.APIS_ENV_VITE_FRONT_URL }} >> .env
          echo "Fichier .env copié avec succès"

      - name: 📤 Copier le fichier .env.db du back
        run: |
          cd /home/runner/work/audit-qcm/audit-qcm/apis
          touch .env.db
          echo ${{ secrets.POSTGRES_USER }} >> .env.db
          echo ${{ secrets.POSTGRES_PASSWORD }} >> .env.db
          echo ${{ secrets.POSTGRES_DB }} >> .env.db
          echo "Fichier .env.db copié avec succès"

      - name: 📤 Copier le fichier .env du front
        run: |
          cd /home/runner/work/audit-qcm/audit-qcm/apps
          touch .env
          echo ${{ secrets.APP_ENV }} >> .env
          echo "Fichier .env du front copié avec succès"

      # 2. Cache des dépendances Node.js (si applicable)
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/apis/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # 3. Installer Docker et Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo apt-get install -y docker-compose
          sudo usermod -aG docker $USER  # Donne les droits d'exécution à Docker

      # 4. Lancer Docker Compose
      - name: Run Docker Compose
        run: |
          pwd
          ls -al
          sudo docker volume ls
          sudo docker-compose down || true
          sudo docker-compose up --build -d
          sudo docker image prune -f
          sudo docker ps

      # 5. Vérifier que tous les conteneurs sont bien up
      - name: Verify Docker Containers
        run: |
          docker ps  # Affiche les conteneurs actifs et vérifie leur statut
          docker-compose ps  # Vérifie l'état des conteneurs définis dans docker-compose.yml

  qcm-apis-deploy:
    needs: test-step
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout du code
        uses: actions/checkout@v4

      # 2. Connexion au VPS et préparation du répertoire
      - name: 🔑 Connexion au VPS et préparation du répertoire
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /opt/audit-qcm/apis/
            mkdir -p /opt/audit-qcm/apis/
            echo "Répertoire /opt/audit-qcm/apis/ prêt"

      # 3. Copier les fichiers du Backend vers le VPS (structure respectée)
      - name: 📤 Copier les fichiers Backend sur le VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "apis/*"
          target: /opt/audit-qcm/apis/
          strip_components: 1

      # 4. Copier le fichier .env sur le VPS
      - name: 📤 Copier le fichier .env sur le VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/audit-qcm/apis
            touch .env
            echo ${{ secrets.APIS_ENV_TZ }} >> .env
            echo ${{ secrets.APIS_ENV_PORT }} >> .env
            echo ${{ secrets.APIS_ENV_HOST }} >> .env
            echo ${{ secrets.APIS_ENV_LOG_LEVEL }} >> .env
            echo ${{ secrets.APIS_ENV_APP_KEY }} >> .env
            echo ${{ secrets.APIS_ENV_NODE_ENV }} >> .env
            echo ${{ secrets.APIS_ENV_DB_HOST }} >> .env
            echo ${{ secrets.APIS_ENV_DB_PORT }} >> .env
            echo ${{ secrets.APIS_ENV_DB_USER }} >> .env
            echo ${{ secrets.APIS_ENV_DB_PASSWORD }} >> .env
            echo ${{ secrets.APIS_ENV_DB_DATABASE }} >> .env
            echo ${{ secrets.APIS_ENV_SMTP_HOST }} >> .env
            echo ${{ secrets.APIS_ENV_SMTP_PORT }} >> .env
            echo ${{ secrets.APIS_ENV_SMTP_USERNAME }} >> .env
            echo ${{ secrets.APIS_ENV_SMTP_PASSWORD }} >> .env
            echo ${{ secrets.APIS_ENV_CACHE_VIEWS }} >> .env
            echo ${{ secrets.APIS_ENV_VITE_FRONT_URL }} >> .env
            echo ${{ secrets.POSTGRES_USER }} >> .env
            echo ${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo ${{ secrets.POSTGRES_DB }} >> .env
            echo "Fichier .env copié avec succès sur le VPS"
            echo "copie du .env.db"
            cd /opt/audit-qcm/apis
            touch .env.db
            echo ${{ secrets.POSTGRES_USER }} >> .env.db
            echo ${{ secrets.POSTGRES_PASSWORD }} >> .env.db
            echo ${{ secrets.POSTGRES_DB }} >> .env.db
            echo "Fichier .env.db copié avec succès"

  qcm-apps-deploy:
    needs: qcm-apis-deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout du code
        uses: actions/checkout@v4

      # Cache des dépendances Frontend
      - name: 🚚 Restaurer le cache des dépendances Frontend
        uses: actions/cache@v3
        with:
          path: ./apps/node_modules
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('**/apps/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-modules-

      - name: 📦 Installer les dépendances Frontend
        working-directory: ./apps
        run: npm install

        # Connexion au VPS et préparation du répertoire #chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /opt
      - name: 🔑 Connexion au VPS et préparation du répertoire
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /opt/audit-qcm/apps/
            mkdir -p /opt/audit-qcm/apps
            cd /opt/audit-qcm/apps
            touch .env
            echo ".env ajouté"
            echo "Répertoire /opt/audit-qcm prêt"

      - name: 📤 Copier les fichiers Frontend sur le VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "apps/*"
          target: "/opt/audit-qcm/apps/"
          strip_components: 1

      # Copier le fichier docker-compose.yml sur le VPS
      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yml"
          target: /opt/audit-qcm/

        # Copier le fichier .env sur le VPS
      - name: 📤 Copier le fichier .env sur le VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/audit-qcm/apps
            touch .env
            echo ${{ secrets.APP_ENV }} >> .env

  deploy-docker:
    needs: qcm-apps-deploy
    runs-on: ubuntu-latest
    steps:
      # Etape 2: Connexion au VPS et démarrage des services Docker
      - name: 🔑 Connexion au VPS et démarrer les services Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Aller dans le répertoire où se trouve le docker-compose
            cd /opt/audit-qcm

            # Démarrer les services Docker avec build si nécessaire
            docker-compose up --build -d

            # Supprimer les images non utilisées pour libérer de l'espace
            docker image prune -f

            # Afficher les conteneurs en cours d'exécution
            docker ps
